source "http://127.0.0.1:3001"

gem "rails", "2.3.14"
gem "haml"
gem "sass"
gem "simple-navigation"
gem "i18n"
gem "json", "1.5.2"
gem "thin"
gem "rainbows", "4.4.3"
gem "formtastic", "1.2.4"

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  # bundler requires these gems while running tests
  # gem "rspec"
  # gem "faker"
end

